# Generated by Django 5.1.3 on 2024-11-27 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefone_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_cliente', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orcamento.orcamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_produtos.product')),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='produtos',
            field=models.ManyToManyField(through='app_orcamento.OrcamentoProduto', to='app_produtos.product'),
        ),
    ]
